spring:
  application:
    name: Country and city list

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-request-size: 1MB

server:
  port: ${PORT:8100}

application:
  image-storage:
    path: ${IMAGE_STORAGE_PATH}

#todo logging params for diffenet profiles
#todo explain  param to manual